### ISSUE TITLE
animal model

### ISSUE THREAD

**Issue by JavierMarcuzzi** [matthewwolak/gremlin#26]
Dear
In other alternatives I use ranef, how is it possible to extract the calculated values for fixed and random effects? I am thinking about BLUP and BLUE, in Mrode11 example I would like to know the genetic value for each calf. Logically it would be good to calculate the breeding value, accuracy and heritability. how can I do? Thank you.

**Comment by matthewwolak** [comment]
Hi, Sorry but I am out of the office. I will give you a full answer next
week. The short answer is you can extract the BLUEs and BLUPs, as well as
the standard errors on those estimates/predictions. I will respond later
with more information/code to help.

**Comment by matthewwolak** [comment]
Hi Javier,

Sorry for the delay. `gremlin` has a method to extract fixed effects (BLUEs), but the current version on CRAN (`gremlin v1.1.0`) does not yet contain a method to extract BLUPs. However, you can use the following code to get BLUEs, BLUPs, and heritability standard errors.

# A sire model example:

```{r}
library(gremlin)
grS <- gremlin(WWG11 ~ sex - 1,
  random = ~ sire,
  data = Mrode11)
```
### extract BLUEs (fixed effects)
```{r}
fixef(grS)

## if you want the standard errors, it is easiest to obtain these from the summary
BLUE <- summary(grS)$coefficients
```

### BLUPs (random effects)
Note these will be ALL random effects in the model

```{r}
BLUP <- with(grS$grMod,
  structure(as(tail(sln, -modMats$nb), "matrix"),
    dimnames = list(tail(W@Dimnames[[2L]], -modMats$nb), NULL)))

## Standard Errors for the BLUPs
coefVarScale <- with(grS$grMod,
  ifelse(lambda, sigma2e, 1.0))
BLUP_SE <- with(grS$grMod,
  structure(as(sqrt(coefVarScale * tail(Cinv_ii, -modMats$nb)), "matrix"),
    dimnames = list(tail(W@Dimnames[[2L]], -modMats$nb), NULL)))

```

### residuals
```{r}
res <- residuals(grS)
```

# Animal model and heritability (with standard error)
Since the above sire model example is pretty silly (only 3 unique sires fit as random effects with 5 observed individuals), instead I will fit an animal model (using the `nadiv` package to obtain the inverse relatedness matrix). After showing the same extractions as above (BLUEs and BLUPs) I will use the delta function to calculate the heritability (`h2`) and approximate the standard error.

```{r}
library(nadiv)
Ainv <- makeAinv(prepPed(Mrode11[, 1:3]))$Ainv

grA <- gremlin(WWG11 ~ sex -1,
  random = ~ calf,
  ginverse = list(calf = Ainv),
  data = Mrode11)
# BLUE
BLUE_AM <- summary(grA)$coefficients
# BLUP
## Same note as in the sire model above: this extracts ALL random effect BLUPs
### (so if there are other random effects terms, this code will return all BLUPs)
BLUP_AM <- with(grA$grMod,
  structure(as(tail(sln, -modMats$nb), "matrix"),
    dimnames = list(tail(W@Dimnames[[2L]], -modMats$nb), NULL)))
coefVarScale <- with(grA$grMod,
  ifelse(lambda, sigma2e, 1.0))
BLUP_AM_SE <- with(grA$grMod,
  structure(as(sqrt(coefVarScale * tail(Cinv_ii, -modMats$nb)), "matrix"),
    dimnames = list(tail(W@Dimnames[[2L]], -modMats$nb), NULL)))

# heritability and standard error
deltaSE(h2 ~ V1 / (V1 + V2), grA)
```

**Comment by JavierMarcuzzi** [comment]
Dear Matthew

Thank you very much for your response. I was testing is is faster than Pedigreemm, unfortunately can not make models with two variables, the classic cbind as in MCMCglmm, I try to pass two variables as a single variable, reorganizing, but fails. 

However your alternative seems to me very good.

Possibly it is a good idea to solve the examples of Mrode, they are a great help and reference as those of https://wildanimalmodels.org.

Possibly the MCMCglmm source code can give an example to build the models, for more than one variable or random regressions, however, the R library, sommer, also uses REML but uses c++ armadillo, which I think is very good to use several processors at the same time on the computer, I do not know if the library you use has this capability. 

Your thinking is the clearest for me, your code is fast, better than pedigreemm or MCMCglmm, I could not compare it with R sommer, but possibly the way to assemble the models and the use of armadillo c++ as in sommer and REML can contribute a lot to your work and effort.
If I may, 

I think you should use the examples in Mrode's book as in https://github.com/QTL-rocks/Linear-Models-for-the-Prediction-of-Animal-Breeding-Values and https://wildanimalmodels.org helps a lot to understand how to use his great work.

Congratulations and thank you very much.

I hope I made myself understood, I used a translator and read it as correct.

Javier

Translated with DeepL.com (free version)
